### ISSUE TITLE
Leaflet Coodinate Mapping Tool

### ISSUE THREAD

**Issue by MuchQuak** [Symbiota/Symbiota#526]
# Description
Tool within public Occurrence Search page tool that assists users in creating bounding box, polygon, and point/radius definition to be used within public search. This is a simple map with shape drawing controls with ability to transfer shape to parent form, but no need to map occurrence points

### File path: 

```
/collections/tools/mapcoordaid.php
```
### Examples:
https://lichenportal.org/portal/collections/tools/mapcoordaid.php
Used within:[ https://lichenportal.org/portal/collections/harvestparams.php](https://lichenportal.org/portal/collections/harvestparams.php)

This tool should probably be merged into one of the other polygon tools (e.g. /collections/tools/mapcoordaid.php

# TODO
- [x] Km/miles Conversion
- [x] Refactor to only be js
- [x] Refactor google maps code to be general purpose
- [x] Add Flag to symbini for leaflet enable

**Comment by Atticus29** [comment]
PR for posterity: https://github.com/BioKIC/Symbiota/pull/525
