### ISSUE TITLE
Simple Checklist Map

### ISSUE THREAD

**Issue by MuchQuak** [Symbiota/Symbiota#534]
# Description

Accessible from checklist page as link associated with left-hand map displayed under the option box. Only available for checklists that have linked vouchers with coordinates.  

### File Path:

```
/checklists/checklist.php
```

### Examples:
https://swbiodiversity.org/seinet/checklists/checklistmap.php?clid=2&thesfilter=0&taxonfilter=
Available from: https://swbiodiversity.org/seinet/checklists/checklist.php?clid=2&pid=1 

# TODO
- [x] Parse Markers into LatLngs
- [x] Add Markers to Map
- [x] Parse wkt polygon from checklist manager
- [x] Draw polygon
- [ ] Add on hover popup
- [ ] Add onClick event to specimen
