### ISSUE TITLE
Static Map Thumbnail Service

### ISSUE THREAD

**Issue by MuchQuak** [Symbiota/Symbiota#535]
# Description
Service is used to dynamically generate a jpg thumbnail that represents a distribution of points. Thumbnail is typically used as a graphical display that serves that when clicked on, opens one of the maps below. Thumbnails are displayed within the checklist project and taxon profile pages. 

Central issue is that Google does not allow use to cache thumbnails, thus each page access requires thumbnail to be regenerated, even if the data never changed, thus resulting in a potential costly number of API requests. 

Another is that only 50 point can be mapped per thumbnail, which provides an incomplete representation of the species distribution 

Goal is to create a new service that uses LeafLet that generates jpg files with greater number of point, and/or rendered as a heat map, which are loaded onto the storage mount (e.g. $IMAGE_ROOT) and added to the map table.

Urls generated within classes: MapSupport, TaxonProfile

### File path: 
```
/checklists/checklist.php
```
### Examples:
- https://swbiodiversity.org/seinet/checklists/checklist.php?clid=2&pid=1
- https://swbiodiversity.org/seinet/taxa/index.php?taxauthid=1&taxon=95&clid=2
- https://swbiodiversity.org/seinet/projects/index.php?pid=1  

# TODO
- [ ] Loaded what thumbnail should be in live map
- [ ] Create Function to get snap shot of live map example
- [ ] Integrate into MapSupport Class
- [ ] Integrate into TaxonProfile Class
