### ISSUE TITLE
Map of Checklists

### ISSUE THREAD

**Issue by MuchQuak** [Symbiota/Symbiota#536]
# Description
Renders map with all the checklists represented as markers. Double clicking marker routes user to checklist.

### File path: 
```
/checklists/clgmap.php
```
### Examples:
https://lichenportal.org/portal/checklists/clgmap.php?pid=519 
Accessible within: https://lichenportal.org/portal/projects/index.php?pid=519  

# TODO
- [x] Refactor for Leaflet/Google Maps Toggle
- [x] Move Google Map part of Code to separate file 
- [x] Create Js File for Leaflet part of this code
- [x] Draw Markers at coords
- [x] Add Popups with info about which checklist
- [x] Add onClick route
