### ISSUE TITLE
Occurence profile map

### ISSUE THREAD

**Issue by MuchQuak** [Symbiota/Symbiota#537]
# Description
Maps coordinates for a given specimen. 

### Examples:
https://swbiodiversity.org/seinet/collections/individual/index.php?occid=2027842 
Coordinate error (eg coordianteErrorInMeters) need to be added 

# TODO
- [ ] Refactor Google Code Into seperate Js File
- [ ] Add Leaflet Toggle
- [ ] Create Leafet version
