### ISSUE TITLE
Checklist Polygon def

### ISSUE THREAD

**Issue by MuchQuak** [Symbiota/Symbiota#552]
# Description
Checklist manager defines a polygon that represents geographic area of checklist. This map editor is only available by approved checklist editors. 

### Notes:
- External polygon definitions can be add and tool will formatted into a Symbiota friendly polygon
- Polygon definition needs to be saved into a new format, such as geoJson or wkt with long/lat format 
- This shape is displayed within the simple and dynamic maps when maps are opened via a checklist link

### File path: 
```
/checklists/tools/mappolyaid.php 
```
### Examples:
https://swbiodiversity.org/seinet/checklists/tools/mappolyaid.php?clid=2&formname=editclmatadata&latname=latcentroid&longname=longcentroid&latdef=35.010100&lngdef=-111.780000  

# TODO
- [x] Read over existing code come up with todos
- [x] Refactor google version to separate concerns
- [x] Solve the multi polygon problem by keep internal track of all drawn shapes
- [x] Create Leaflet version
- [x] port sig fix trimming
- [x] port coordinate swapping
- [x] ensure form saves values to parent form and db
